<?
  session_start();
?>
<? 
$Remove["denyreason"];
$Remove["dailypopulationtaxes"];
$Remove["citizens"];
$Remove["totalmoneyavailable"];
$Remove["maximumbuy"];
$Remove["infrastructurecost"];
$Remove["maxsell"];
$Remove["infrastructurecost2"];
$Remove["alreadyused"];
?>
