<textarea rows="20" onFocus="this.blur()" name="S1" cols="62">Cyber Nations is a free online nation simulation game. The nations are not real, the money that your nation earns is certainly not real, the politics, the wars, the religions, none of it is real. Cyber Nation is intended to be a fun place to try your hand at ruling a simulated nation. What is real are the players of Cyber Nations. Rude, inappropriate, threatening, malicious, defamatory, or obscene comments, messages, ruler names, nation names or bios or any other such content is not permitted. If such content is discovered you will be removed from the game. Keep in mind that while using this site there are many more players than moderators and you may run across content that you find objectionable. While reasonable efforts will be exerted to ensure the site remains free from offensive and illegal content, the site administrator(s) and/or moderator(s) are not responsible for what other people upload to this system. You understand that in this case that Cyber Nations is a not a publisher and is not responsible for content and information posted by its players. 

Cheating in the form of abusing the war system, foreign aid system, trade system, etc... with multiple accounts controlled by the same player and other such activities is strictly not allowed. Multiple accounts from the same computer network, even if managed by different individuals are not allowed to interact in the game. If you come across an exploit please report it to the appropriate administrator(s) and/or moderator(s). If you use the exploit you will be removed from this website. Do not, under any circumstance run scripts of any kind against this website. Nation deletions can occur at any time by the Cyber Nations administrator(s) and/or moderator(s) at their discretion. If your nation is left inactive for more than 20 days it will be deleted (activity is updated only during tax collection). The game is still in beta as it is still new and as a result game features, demographics, statistics, calculations, and everything else may be subject to change at any time. 

Cyber Nations is privately owned and operated. It exists because of the generous donations made by its players to help support the systems and applications that run the game. Donations are completely voluntary. Players are NOT required to donate to play Cyber Nations. If a player should voluntarily leave the game, if a player's nation is deleted by the player him/her self or banned by administration for ANY REASON (cheating, violating TOS, violating official forum guidelines, 20 days inactivity, unstated reasons, etc...) or if the game is ever shut down or reset NO REFUNDS and NO compensation will be provided to the player or to any re-created nation. Sending a payment that is reversed, denied, or does not clear after the donation bonus has been provided will result in nation deletion since donation bonuses cannot be reversed once applied towards a nation.

When you submit information to Cyber Nations, you grant ownership of such content to the site and its administrator(s) a non-exclusive, royalty-free, worldwide, perpetual license to reproduce, distribute, transmit, and publicly display such content. You may not attempt to sell or profit from any such content or information via private exchanges without administrative consent. Such private exchanges that are forbidden include nation selling, war outsourcing, foreign aid for real life money outside of the official Cyber Nations donation system, and any other private exchange where individuals attempt to profit from the game. If you are found to be attempting to profit via private exchanges from Cyber Nations and in breech of these terms and conditions you will be removed from this website.  

By using this site you certify that you are at least thirteen years of age or have your legal guardian’s permission to use this website and/or its forums. Where your country of access imposes laws regulating this web site, you agree to use your best efforts to comply with them.

Cyber Nations reserves the right to make changes to these Terms and Conditions immediately by posting the changed Terms and Conditions in this location. Your continued use of this web site constitutes your agreement to all such terms, conditions and notices, and any changes to the Terms and Conditions made by Cyber Nations. If you are found in breech of the terms of this website or the Cyber Nations community forums your nation will be subject to deletion and or banning from the game. USE THE WEB SITE AT YOUR OWN RISK. THIS WEB SITE IS PROVIDED TO YOU "AS IS," WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. If you do not agree to these terms and conditions DO NOT use this site. Should you breach these terms and conditions you agree to indemnify Cyber Nations, and any and all employees, agents, administrators, moderators, volunteers, and affiliates associated with Cyber Nations from and against any and all third party claims, demands, liabilities, costs or expenses, and legal fees. Last Updated: 1/19/2007
</textarea>
